<a href="https://colab.research.google.com/github/Anandxz/Machine-Learning/blob/main/Numpy_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

ARRAY CREATION

In [3]:
arr1d=np.array([1,2,3,4,5])
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
print("1D ARRAY:",arr1d)

1D ARRAY: [1 2 3 4 5]


In [5]:
print("2D ARRAY",arr2d)

2D ARRAY [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print("Array Shape",arr1d.shape)

Array Shape (5,)


In [7]:
print("Array Shape",arr1d.dtype)

Array Shape int64


In [8]:
print("Array Shape",arr2d.shape)

Array Shape (3, 3)


Creating Arrys with built-in function


In [15]:
zeros=np.zeros((3,4)) #3*3 array of zeros
ones=np.ones((2,3))
range_arr=np.arange(0,10,2)
linspace_arr=np.linspace(0,0.5,3)
print("\nZeros array:\n", zeros)
print("\nOnes array:\n", ones)
print("Range array:", range_arr)
print("Linspace array:", linspace_arr) # 5 evenly spaced values from 0 to 1


Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5 ]


#BASIC OPERATION


# Element-wise arithmetic operations

In [25]:
a=np.array([1,2,3,4])

In [26]:
b=np.array([5,6,7,8])

In [27]:
print("---Basic Operations---")
print("a=",a)
print("b=",b)
print("a+b=",a+b)
print("a * b =", a * b)  # Element-wise multiplication
print("a ** 2 =", a ** 2)

---Basic Operations---
a= [1 2 3 4]
b= [5 6 7 8]
a+b= [ 6  8 10 12]
a * b = [ 5 12 21 32]
a ** 2 = [ 1  4  9 16]


# Broadcasting - operations with different shapes

In [33]:
matrix=np.array([[1,2,3],[4,5,6]])
scalar=10
vector=np.array([1,2,3])

In [34]:
print("\nMatrix:\n", matrix)
print("Matrix + scalar:\n", matrix + scalar)  # Adds 10 to each element
print("Matrix + vector:\n", matrix + vector)  # Adds vector to each row



Matrix:
 [[1 2 3]
 [4 5 6]]
Matrix + scalar:
 [[11 12 13]
 [14 15 16]]
Matrix + vector:
 [[2 4 6]
 [5 7 9]]


In [35]:
data = np.array([1, 4, 9, 16, 25])
print("\nSquare roots:", np.sqrt(data))
print("Natural log:", np.log(data))
print("Sine values:", np.sin(np.pi * np.array([0, 0.5, 1])))



Square roots: [1. 2. 3. 4. 5.]
Natural log: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
Sine values: [0.0000000e+00 1.0000000e+00 1.2246468e-16]


#Aggreagation Function

In [36]:
matrix_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [37]:
print("---Aggregation Functions---")
print("Matrix:\n", matrix_2d)
print("\nSum of all array\n",np.sum(matrix_2d))
print("\nSum along axis 0(coloumn)\n",np.sum(matrix_2d,axis=0))
print("\nSum along axis 1\n",np.sum(matrix_2d,axis=1))
print("\nMean\n",np.mean(matrix_2d))
print("\n Standerd Deviation \n",np.std(matrix_2d))
print("\nVariance\n",np.var(matrix_2d))
print("\nMax value\n",np.max(matrix_2d))
print("\nMin value\n",np.min(matrix_2d))
print("\nMax value index\n",np.argmax(matrix_2d))
print("\nMin value index\n",np.argmin(matrix_2d))
print("\nCumulative sum\n",np.cumsum(matrix_2d))
print("\nCumulative product\n",np.cumprod(matrix_2d))

---Aggregation Functions---
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of all array
 45

Sum along axis 0(coloumn)
 [12 15 18]

Sum along axis 1
 [ 6 15 24]

Mean
 5.0

 Standerd Deviation 
 2.581988897471611

Variance
 6.666666666666667

Max value
 9

Min value
 1

Max value index
 8

Min value index
 0

Cumulative sum
 [ 1  3  6 10 15 21 28 36 45]

Cumulative product
 [     1      2      6     24    120    720   5040  40320 362880]


#Indexing & Sum


In [38]:
# 1D array indexing
arr = np.array([10, 20, 30, 40, 50])
print("\n--- 1D Indexing ---")
print("Array:", arr)
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Slice [1:4]:", arr[1:4])  # Elements at indices 1, 2, 3
print("Every other element:", arr[::2])


--- 1D Indexing ---
Array: [10 20 30 40 50]
First element: 10
Last element: 50
Slice [1:4]: [20 30 40]
Every other element: [10 30 50]


In [39]:
# 2D array indexing
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [48]:
print("\n--- 2D Indexing ---")
print("Matrix:\n", matrix)
print("Element at (1,2):", matrix[1, 2])  # Row 1, Column 2
print("First row:", matrix[0, :])
print("Second column:", matrix[:, 1])
print("Submatrix [1:2, 1:3]:\n", matrix[0:2, 0:3])


--- 2D Indexing ---
Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element at (1,2): 7
First row: [1 2 3 4]
Second column: [ 2  6 10]
Submatrix [1:2, 1:3]:
 [[1 2 3]
 [5 6 7]]


In [49]:
# Fancy indexing (using arrays of indices)
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([1, 3, 4])
print("\n--- Fancy Indexing ---")
print("Array:", arr)
print("Elements at indices [1,3,4]:", arr[indices])


--- Fancy Indexing ---
Array: [10 20 30 40 50]
Elements at indices [1,3,4]: [20 40 50]


In [50]:
# 2D fancy indexing
matrix = np.array([[1, 2], [3, 4], [5, 6]])
row_indices = np.array([0, 2])
col_indices = np.array([1, 0])
print("Matrix:\n", matrix)
print("Fancy indexing result:", matrix[row_indices, col_indices])  # (0,1) and (2,0)

Matrix:
 [[1 2]
 [3 4]
 [5 6]]
Fancy indexing result: [2 5]


In [51]:
# Reshaping arrays
original = np.arange(12)
reshaped = original.reshape(3, 4)
print("\n--- Shape Manipulation ---")
print("Original (12,):", original)
print("Reshaped (3,4):\n", reshaped)
print("Flattened:", reshaped.flatten())


--- Shape Manipulation ---
Original (12,): [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped (3,4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [52]:
# Transpose
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Original matrix:\n", matrix)
print("Transposed:\n", matrix.T)
print("Flattened:", matrix.flatten())

Original matrix:
 [[1 2 3]
 [4 5 6]]
Transposed:
 [[1 4]
 [2 5]
 [3 6]]
Flattened: [1 2 3 4 5 6]
